import { siteConfig } from "@/content/site-config";
import {
  isPublishedProduct,
  type DraftProduct,
  type Product,
} from "@/types/product";

const createDraftProduct = (
  product: Omit<DraftProduct, "model" | "status" | "storeUrl">,
): DraftProduct => ({
  ...product,
  model: null,
  status: "draft",
  storeUrl: siteConfig.storeUrl,
});

export const products: readonly Product[] = [
  createDraftProduct({
    slug: "noel-baba-ren-geyigi-led-dekor",
    name: "Noel Baba ve Ren Geyiği LED Dekor",
    category: "Dekoratif Aydınlatma",
    description: "Noel Baba, ren geyiği ve sıcak ışıklı kamp ateşi detaylarından oluşan dekoratif sahne.",
    image: "/images/products/noel-baba-ren-geyigi-led-dekor.webp",
    imageAlt: "Işıklı kamp ateşinin yanında oturan Noel Baba ve ren geyiği dekoru",
    scene: "dark-studio",
  }),
  createDraftProduct({
    slug: "ciri-diorama",
    name: "Ciri Savaşçı Dioraması",
    category: "Koleksiyon Figürü",
    description: "Kılıç, zincir ve yaratık taban detaylarıyla tamamlanan, el boyaması savaşçı dioraması.",
    image: "/images/products/ciri-diorama.webp",
    imageAlt: "Kılıç ve zincir taşıyan Ciri savaşçı dioraması",
    scene: "dark-studio",
  }),
  createDraftProduct({
    slug: "hollow-knight-figur",
    name: "Hollow Knight Figürü",
    category: "Koleksiyon Figürü",
    description: "Kristal, bitki ve mızrak detaylarıyla hazırlanmış dekoratif Hollow Knight figürü.",
    image: "/images/products/hollow-knight-figur.webp",
    imageAlt: "Mor kristalli taban üzerinde Hollow Knight figürü",
    scene: "dark-studio",
  }),
  createDraftProduct({
    slug: "marcus-aurelius-bustu",
    name: "Marcus Aurelius Büstü",
    category: "Büst",
    description: "Klasik portre ile kafatası formunu iki farklı yüzeyde birleştiren dekoratif büst.",
    image: "/images/products/marcus-aurelius-bustu.webp",
    imageAlt: "Yarısı klasik portre yarısı kafatası olan Marcus Aurelius büstü",
    scene: "white-studio",
  }),
  createDraftProduct({
    slug: "forest-dragon-bustu",
    name: "Forest Dragon Büstü",
    category: "Büst",
    description: "Organik boynuzlar, pullar ve ağaç dokusunu çağrıştıran ayrıntılara sahip ejderha büstü.",
    image: "/images/products/forest-dragon-bustu.webp",
    imageAlt: "Mor ışık altında boynuzlu Forest Dragon büstü",
    scene: "purple-gallery",
  }),
  createDraftProduct({
    slug: "lotus-buda-tutsuluk",
    name: "Lotus Çiçeği Buda Tütsülük",
    category: "Tütsülük",
    description: "Lotus yapraklarının merkezinde Buda figürü bulunan iki renkli dekoratif tütsülük.",
    image: "/images/products/lotus-buda-tutsuluk.webp",
    imageAlt: "Mor lotus yapraklarının ortasında beyaz Buda figürlü tütsülük",
    scene: "dark-studio",
  }),
  createDraftProduct({
    slug: "yuzuklerin-efendisi-masa-susu",
    name: "Yüzüklerin Efendisi Masa Süsü",
    category: "Masa Süsü",
    description: "Yazılı yüzük formu içinde üç karanlık süvari figürü bulunan tematik masa dekoru.",
    image: "/images/products/yuzuklerin-efendisi-masa-susu.webp",
    imageAlt: "Yüzük biçimli kaide içinde üç karanlık süvari figürü",
    scene: "white-studio",
  }),
  createDraftProduct({
    slug: "link-bustu",
    name: "Link Büstü",
    category: "Büst",
    description: "Kılıcını kaldıran Link karakterini bitki ve taş taban detaylarıyla sunan boyalı büst.",
    image: "/images/products/link-bustu.webp",
    imageAlt: "Yeşil kıyafeti ve kılıcıyla boyanmış Link büstü",
    scene: "dark-studio",
  }),
  createDraftProduct({
    slug: "sevimli-kedi-anahtarlik",
    name: "Sevimli Kedi Anahtarlık",
    category: "Anahtarlık",
    description: "Yumuşak renkleri ve minimal yüz detaylarıyla hazırlanmış sevimli kedi anahtarlık.",
    image: "/images/products/sevimli-kedi-anahtarlik.webp",
    imageAlt: "Pembe yanaklı açık renk kedi anahtarlık",
    scene: "dark-studio",
  }),
  createDraftProduct({
    slug: "el-figurlu-saksi",
    name: "El Figürlü Saksı",
    category: "Saksı",
    description: "Bir çift figüratif el tarafından taşınan yuvarlak gövdeli dekoratif saksı.",
    image: "/images/products/el-figurlu-saksi.webp",
    imageAlt: "Siyah ve altın renkli el figürlerinin taşıdığı yuvarlak saksı",
    scene: "white-studio",
  }),
  createDraftProduct({
    slug: "modern-ikili-vazo",
    name: "Modern İkili Vazo",
    category: "Vazo",
    description: "Birbirine geçen iki organik gövdeden oluşan çağdaş ve heykelsi vazo tasarımı.",
    image: "/images/products/modern-ikili-vazo.webp",
    imageAlt: "Birbirine geçen iki açık renk organik vazo",
    scene: "dark-studio",
  }),
  createDraftProduct({
    slug: "hayalet-kedi-figur",
    name: "Hayalet Kedi Figürü",
    category: "Dekoratif Figür",
    description: "Çarşaf görünümü, küçük patileri ve kulaklarıyla tasarlanmış sevimli hayalet kedi.",
    image: "/images/products/hayalet-kedi-figur.webp",
    imageAlt: "Beyaz çarşaf görünümünde küçük hayalet kedi figürü",
    scene: "dark-studio",
  }),
  createDraftProduct({
    slug: "sauron-figur",
    name: "Sauron Figürü",
    category: "Koleksiyon Figürü",
    description: "Zırh, miğfer ve uzun pelerin detaylarıyla hazırlanmış karanlık savaşçı figürü.",
    image: "/images/products/sauron-figur.webp",
    imageAlt: "Siyah zırhı ve uzun peleriniyle Sauron figürü",
    scene: "white-studio",
  }),
  createDraftProduct({
    slug: "tavsan-kafatasi-anahtarlik-mavi",
    name: "Mavi Tavşan Kafatası Anahtarlık",
    category: "Anahtarlık",
    description: "Kanat benzeri kulak detaylarına sahip mavi renkli stilize tavşan kafatası anahtarlık.",
    image: "/images/products/tavsan-kafatasi-anahtarlik-mavi.webp",
    imageAlt: "Mavi renkli stilize tavşan kafatası anahtarlık",
    scene: "dark-studio",
  }),
  createDraftProduct({
    slug: "tavsan-kafatasi-anahtarlik-gri",
    name: "Gri Tavşan Kafatası Anahtarlık",
    category: "Anahtarlık",
    description: "Kanat benzeri kulak detaylarına sahip gri renkli stilize tavşan kafatası anahtarlık.",
    image: "/images/products/tavsan-kafatasi-anahtarlik-gri.webp",
    imageAlt: "Gri renkli stilize tavşan kafatası anahtarlık",
    scene: "dark-studio",
  }),
  createDraftProduct({
    slug: "tavsan-kafatasi-anahtarlik-pembe",
    name: "Pembe Tavşan Kafatası Anahtarlık",
    category: "Anahtarlık",
    description: "Kanat benzeri kulak detaylarına sahip pembe renkli stilize tavşan kafatası anahtarlık.",
    image: "/images/products/tavsan-kafatasi-anahtarlik-pembe.webp",
    imageAlt: "Pembe renkli stilize tavşan kafatası anahtarlık",
    scene: "dark-studio",
  }),
  createDraftProduct({
    slug: "noel-sapkali-balik-anahtarlik",
    name: "Noel Şapkalı Balık Anahtarlık",
    category: "Anahtarlık",
    description: "Noel şapkası ayrıntısıyla tamamlanan sevimli balık formunda anahtarlık.",
    image: "/images/products/noel-sapkali-balik-anahtarlik.webp",
    imageAlt: "Kırmızı Noel şapkası takan açık renk balık anahtarlık",
    scene: "dark-studio",
  }),
  createDraftProduct({
    slug: "spider-man-venom-bustu",
    name: "Spider-Man ve Venom Büstü",
    category: "Büst",
    description: "Spider-Man ve Venom formlarını tek portrede birleştiren, çok parçalı boyalı büst.",
    image: "/images/products/spider-man-venom-bustu.webp",
    imageAlt: "Yarısı Spider-Man yarısı Venom olarak tasarlanmış büst",
    scene: "white-studio",
  }),
  createDraftProduct({
    slug: "fantastik-karambit",
    name: "Fantastik Karambit",
    category: "Dekoratif Aksesuar",
    description: "Keskin hatlar ve mor vurgularla tasarlanmış, oyun estetiğinden ilham alan dekoratif karambit.",
    image: "/images/products/fantastik-karambit.webp",
    imageAlt: "Gri, siyah ve mor renkli fantastik karambit modeli",
    scene: "dark-studio",
  }),
  createDraftProduct({
    slug: "lilith-bustu",
    name: "Lilith Büstü",
    category: "Büst",
    description: "Boynuzlu başlık, zırh ve el boyaması yüz detaylarıyla hazırlanmış fantastik karakter büstü.",
    image: "/images/products/lilith-bustu.webp",
    imageAlt: "Boynuzlu başlığı ve zırhıyla boyanmış Lilith büstü",
    scene: "dark-studio",
  }),
  createDraftProduct({
    slug: "samuray-savasci-diorama",
    name: "Samuray Savaşçı Dioraması",
    category: "Koleksiyon Figürü",
    description: "Kılıçlı savaşçı, mimari parçalar ve sahne tabanıyla tamamlanan boyalı samuray dioraması.",
    image: "/images/products/samuray-savasci-diorama.webp",
    imageAlt: "Kılıç taşıyan samuray savaşçının boyalı dioraması",
    scene: "dark-studio",
  }),
  createDraftProduct({
    slug: "karanlik-orman-buyucusu-diorama",
    name: "Karanlık Orman Büyücüsü Dioraması",
    category: "Koleksiyon Figürü",
    description: "Kapüşonlu figür, dallanan asa ve orman tabanı ayrıntılarıyla hazırlanan fantastik diorama.",
    image: "/images/products/karanlik-orman-buyucusu-diorama.webp",
    imageAlt: "Dallı asa tutan kapüşonlu karanlık orman büyücüsü dioraması",
    scene: "white-studio",
  }),
  createDraftProduct({
    slug: "tenjin-samuray-bustu",
    name: "Tenjin Samuray Büstü",
    category: "Büst",
    description: "Katmanlı zırh, boynuzlu miğfer ve metalik boya detaylarıyla hazırlanmış samuray büstü.",
    image: "/images/products/tenjin-samuray-bustu.webp",
    imageAlt: "Tenjin yazılı kaide üzerinde altın zırhlı samuray büstü",
    scene: "dark-studio",
  }),
  createDraftProduct({
    slug: "kutuda-kedi-anahtarlik",
    name: "Kutuda Kedi Anahtarlık",
    category: "Anahtarlık",
    description: "Açılır kutudan çıkan büyük gözlü kedi figürüyle tasarlanmış hareketli anahtarlık.",
    image: "/images/products/kutuda-kedi-anahtarlik.webp",
    imageAlt: "Turuncu kutudan çıkan beyaz kedi figürlü anahtarlık",
    scene: "dark-studio",
  }),
  createDraftProduct({
    slug: "mavi-canavar-iskelet-anahtarlik",
    name: "Mavi Canavar İskelet Anahtarlık",
    category: "Anahtarlık",
    description: "Mavi canavar kostümü içindeki küçük iskelet karakteriyle hazırlanmış anahtarlık.",
    image: "/images/products/mavi-canavar-iskelet-anahtarlik.webp",
    imageAlt: "Mavi canavar kostümü giymiş küçük iskelet anahtarlık",
    scene: "dark-studio",
  }),
  createDraftProduct({
    slug: "kutuda-foklar-anahtarlik",
    name: "Kutuda Foklar Anahtarlık",
    category: "Anahtarlık",
    description: "Kırmızı açılır kutu içinde üç minik fok figürü bulunan eğlenceli anahtarlık.",
    image: "/images/products/kutuda-foklar-anahtarlik.webp",
    imageAlt: "Kırmızı kutu içinde üç beyaz fok figürlü anahtarlık",
    scene: "dark-studio",
  }),
  createDraftProduct({
    slug: "luffy-gear-5-figur",
    name: "Luffy Gear 5 Figürü",
    category: "Koleksiyon Figürü",
    description: "Bulut ve şimşek efektli dinamik tabanı üzerinde hareket halinde tasarlanmış karakter figürü.",
    image: "/images/products/luffy-gear-5-figur.webp",
    imageAlt: "Bulut ve şimşek efektli taban üzerinde Luffy Gear 5 figürü",
    scene: "dark-studio",
  }),
  createDraftProduct({
    slug: "satoru-gojo-kor-bantli-figur",
    name: "Satoru Gojo Kör Bantlı Figür",
    category: "Koleksiyon Figürü",
    description: "Göz bandı, mor enerji formu ve kayalık taban ayrıntılarıyla hazırlanan koleksiyon figürü.",
    image: "/images/products/satoru-gojo-kor-bantli-figur.webp",
    imageAlt: "Göz bandı takan Satoru Gojo figürü ve mor enerji tabanı",
    scene: "purple-gallery",
  }),
  createDraftProduct({
    slug: "satoru-gojo-figur",
    name: "Satoru Gojo Figürü",
    category: "Koleksiyon Figürü",
    description: "Yüzü açık karakter pozu, mor enerji formu ve detaylı kayalık tabanla tamamlanan figür.",
    image: "/images/products/satoru-gojo-figur.webp",
    imageAlt: "Yüzü açık Satoru Gojo figürü ve mor enerji tabanı",
    scene: "purple-gallery",
  }),
  createDraftProduct({
    slug: "chun-li-figur",
    name: "Chun-Li Figürü",
    category: "Koleksiyon Figürü",
    description: "Köprü, taş zemin ve su efekti ayrıntılarıyla dinamik dövüş pozunda hazırlanan figür.",
    image: "/images/products/chun-li-figur.webp",
    imageAlt: "Köprü ve su efektli taban üzerinde Chun-Li figürü",
    scene: "dark-studio",
  }),
];

export const publishedProducts = products.filter(isPublishedProduct);
